#!/usr/bin/env bash
set -euo pipefail

usage() {
  cat <<'EOF'
Usage:
  record_two_devices.sh --session <session.env> [options] [-- command ...]

Options:
  --output <directory>  Evidence directory (default: SESSION_DIR/evidence)
  --seconds <1-600>     Maximum complete recording window (default: 360)
  --bit-rate <integer>  Bits per second for each native segment (default: 8000000)
  --phone-max-edge <2-4096>   Even maximum encoded phone edge (default: native)
  --tablet-max-edge <2-4096>  Even maximum encoded tablet edge (default: native)

Android caps one screenrecord process at 180 seconds. This tool rotates native
170-second segments on both AVDs until the command exits or the complete window
expires. It retains every native segment and also losslessly concatenates each
device's segments when ffmpeg is available.
Output caps preserve the current display aspect and orientation, rounding down
to even pixels. They do not resize the Android display or the app UI.
EOF
}

session_file=''
output_dir=''
duration=360
max_duration=600
bit_rate=8000000
phone_max_edge=''
tablet_max_edge=''
declare -a showcase_command=()

while (( $# > 0 )); do
  case "$1" in
    --session) session_file="${2:-}"; shift 2 ;;
    --output) output_dir="${2:-}"; shift 2 ;;
    --seconds) duration="${2:-}"; shift 2 ;;
    --bit-rate) bit_rate="${2:-}"; shift 2 ;;
    --phone-max-edge) phone_max_edge="${2:-invalid}"; shift 2 ;;
    --tablet-max-edge) tablet_max_edge="${2:-invalid}"; shift 2 ;;
    --) shift; showcase_command=("$@"); break ;;
    -h|--help) usage; exit 0 ;;
    *) echo "Unknown argument: $1" >&2; usage >&2; exit 2 ;;
  esac
done

if [[ -z "$session_file" || ! -f "$session_file" ]]; then
  echo 'A valid --session file from launch_two_avds.sh is required.' >&2
  exit 2
fi
if [[ ! "$duration" =~ ^[0-9]+$ ]] || \
    (( duration < 1 || duration > max_duration )); then
  echo "--seconds must be an integer from 1 through $max_duration." >&2
  exit 2
fi
if [[ ! "$bit_rate" =~ ^[0-9]+$ ]] || (( bit_rate < 1000000 )); then
  echo '--bit-rate must be an integer of at least 1000000.' >&2
  exit 2
fi
for label in phone tablet; do
  cap_variable="${label}_max_edge"
  cap="${!cap_variable}"
  if [[ -n "$cap" ]] && { [[ ! "$cap" =~ ^[1-9][0-9]{0,3}$ ]] || \
      (( cap < 2 || cap > 4096 || cap % 2 != 0 )); }; then
    echo "--$label-max-edge must be an even integer from 2 through 4096." >&2
    exit 2
  fi
done

# session.env is generated by launch_two_avds.sh and contains shell-escaped
# values only. Do not use an untrusted file here.
source "$session_file"
: "${ADB:?session is missing ADB}"
: "${PHONE_SERIAL:?session is missing PHONE_SERIAL}"
: "${TABLET_SERIAL:?session is missing TABLET_SERIAL}"
: "${SESSION_DIR:?session is missing SESSION_DIR}"

output_dir="${output_dir:-$SESSION_DIR/evidence}"
phone_dir="$output_dir/phone-$PHONE_SERIAL"
tablet_dir="$output_dir/tablet-$TABLET_SERIAL"
control_dir="$output_dir/recorder-control"
mkdir -p "$output_dir"
if find "$output_dir" -mindepth 1 -print -quit | grep -q .; then
  echo "Evidence output must be empty before a fresh recording: $output_dir" >&2
  exit 3
fi
mkdir -p "$phone_dir/segments" "$tablet_dir/segments" "$control_dir"

require_device() {
  local serial="$1"
  if [[ "$($ADB -s "$serial" get-state 2>/dev/null || true)" != 'device' ]]; then
    echo "Android device is unavailable: $serial" >&2
    exit 3
  fi
  local existing="$($ADB -s "$serial" shell pidof screenrecord 2>/dev/null | tr -d '\r\n')"
  if [[ -n "$existing" ]]; then
    echo "Refusing to interfere with an existing recorder on $serial: $existing" >&2
    exit 3
  fi
}
require_device "$PHONE_SERIAL"
require_device "$TABLET_SERIAL"

retry_exact_device_command() {
  local serial="$1"
  local command_timeout="$2"
  shift 2
  local attempt
  local state
  for attempt in 1 2 3; do
    state="$(timeout --signal=TERM --kill-after=2s 5s \
      "$ADB" -s "$serial" get-state 2>/dev/null || true)"
    if [[ "$state" == device ]] && \
       timeout --signal=TERM --kill-after=2s "${command_timeout}s" \
         "$ADB" -s "$serial" "$@"; then
      return 0
    fi
    if [[ "$attempt" -lt 3 ]]; then
      sleep 1
    fi
  done
  return 1
}

capture_before() {
  local label="$1"
  local serial="$2"
  local destination="$3"
  "$ADB" -s "$serial" shell getprop > "$destination/properties.txt"
  "$ADB" -s "$serial" shell wm size > "$destination/wm-size.txt"
  "$ADB" -s "$serial" shell wm density > "$destination/wm-density.txt"
  "$ADB" -s "$serial" shell dumpsys display > "$destination/display-before.txt"
  "$ADB" -s "$serial" shell dumpsys window displays > "$destination/window-before.txt"
  "$ADB" -s "$serial" exec-out screencap -p > "$destination/before.png"
  "$ADB" -s "$serial" logcat -c
  printf '%s\t%s\t%s\n' "$label" "$serial" "$(date -u +%Y-%m-%dT%H:%M:%SZ)" \
    > "$destination/identity.tsv"
}
capture_before phone "$PHONE_SERIAL" "$phone_dir"
capture_before tablet "$TABLET_SERIAL" "$tablet_dir"

configure_output_size() {
  local label="$1"
  local display_file="$2"
  local cap="$3"
  local source_size
  source_size="$(awk '
    /Display: mDisplayId=/ { primary = ($0 ~ /mDisplayId=0([[:space:]]|$)/) }
    primary && / cur=/ {
      sub(/.* cur=/, ""); sub(/[[:space:]].*/, ""); print
    }
  ' "$display_file")"
  printf -v "${label}_source_size" '%s' "${source_size:-unknown}"
  printf -v "${label}_output_size" '%s' ''
  if [[ -z "$cap" ]]; then return; fi
  if [[ ! "$source_size" =~ ^([1-9][0-9]{0,4})x([1-9][0-9]{0,4})$ ]]; then
    echo "Cannot determine the current default display size for $label." >&2
    return 3
  fi
  local width="${BASH_REMATCH[1]}"
  local height="${BASH_REMATCH[2]}"
  local longest="$width"
  if (( height > longest )); then longest="$height"; fi
  if (( cap > longest )); then cap="$longest"; fi
  width=$(( width * cap / longest / 2 * 2 ))
  height=$(( height * cap / longest / 2 * 2 ))
  if (( width < 2 || height < 2 )); then
    echo "The $label output cap would collapse a display dimension below 2 pixels." >&2
    return 3
  fi
  printf -v "${label}_output_size" '%s' "${width}x${height}"
}
remote_suffix="$(date -u +%Y%m%dT%H%M%SZ)-$$"
phone_remote_dir="/sdcard/meowwatch-evidence-$remote_suffix-phone"
tablet_remote_dir="/sdcard/meowwatch-evidence-$remote_suffix-tablet"
for spec in \
  "$PHONE_SERIAL:$phone_remote_dir:$phone_dir" \
  "$TABLET_SERIAL:$tablet_remote_dir:$tablet_dir"; do
  serial="${spec%%:*}"
  remainder="${spec#*:}"
  remote_dir="${remainder%%:*}"
  destination="${remainder#*:}"
  if ! "$ADB" -s "$serial" shell mkdir -p "$remote_dir" \
      >> "$destination/screenrecord.log" 2>&1; then
    echo "Could not create the owned Android recording directory on $serial." >&2
    "$ADB" -s "$PHONE_SERIAL" shell rmdir "$phone_remote_dir" >/dev/null 2>&1 || true
    "$ADB" -s "$TABLET_SERIAL" shell rmdir "$tablet_remote_dir" >/dev/null 2>&1 || true
    exit 4
  fi
done

record_segments() {
  local label="$1"
  local serial="$2"
  local remote_dir="$3"
  local destination="$4"
  local stop_file="$control_dir/$label.stop"
  local pid_file="$control_dir/$label.pid"
  local ready_file="$control_dir/$label.ready"
  local timing_file="$control_dir/$label-segments.tsv"
  local segment=0
  local output_size_variable="${label}_output_size"
  local source_size_variable="${label}_source_size"
  local cap_variable="${label}_max_edge"
  local output_size=''
  local -a size_args=()

  while [[ ! -e "$stop_file" ]]; do
    local segment_name
    segment_name="$(printf '%s-%03d.mp4' "$label" "$segment")"
    local remote_segment="$remote_dir/$segment_name"
    local segment_log="$destination/segments/$segment_name.screenrecord.log"
    local display_file="$destination/segments/$segment_name.window-before.txt"
    if ! timeout --signal=TERM --kill-after=2s 10s \
        "$ADB" -s "$serial" shell dumpsys window displays > "$display_file"; then
      touch "$control_dir/$label.failed"
      return 1
    fi
    if ! configure_output_size "$label" "$display_file" "${!cap_variable}"; then
      touch "$control_dir/$label.failed"
      return 1
    fi
    output_size="${!output_size_variable}"
    size_args=()
    if [[ -n "$output_size" ]]; then size_args=(--size "$output_size"); fi
    printf '%s\t%s\t%s\t%s\n' "$segment" "$segment_name" \
      "${!source_size_variable}" "${output_size:-native}" \
      >> "$destination/recording-sizes.tsv"
    local command_ns
    command_ns="$(date +%s%N)"
    timeout --signal=TERM --kill-after=5s 180s \
      "$ADB" -s "$serial" shell screenrecord \
        "${size_args[@]}" \
        --bit-rate "$bit_rate" \
        --time-limit 170 \
        "$remote_segment" \
        > "$segment_log" 2>&1 &
    local host_pid=$!

    local remote_pid=''
    local deadline=$((SECONDS + 10))
    while (( SECONDS < deadline )); do
      remote_pid="$($ADB -s "$serial" shell pidof screenrecord 2>/dev/null \
        | tr -d '\r\n' || true)"
      if [[ "$remote_pid" =~ ^[0-9]+$ ]]; then
        break
      fi
      sleep 0.25
    done
    if [[ ! "$remote_pid" =~ ^[0-9]+$ ]]; then
      echo "$label recorder PID was not uniquely identified." \
        >> "$destination/screenrecord.log"
      touch "$control_dir/$label.failed"
      wait "$host_pid" 2>/dev/null || true
      if ! retry_exact_device_command "$serial" 8 shell rm -f "$remote_segment" \
          >> "$destination/screenrecord.log" 2>&1; then
        touch "$control_dir/$label.cleanup-warning"
      fi
      return 1
    fi

    printf '%s\n' "$remote_pid" > "$pid_file"
    printf '%s\t%s\t%s\n' "$segment" "$command_ns" "$segment_name" \
      >> "$timing_file"
    if [[ "$segment" -eq 0 ]]; then
      printf '%s\n' "$command_ns" > "$ready_file"
    fi
    wait "$host_pid" 2>/dev/null || true
    rm -f "$pid_file"
    local local_segment="$destination/segments/$segment_name"
    local partial_segment="$local_segment.partial"
    rm -f "$partial_segment"
    if ! retry_exact_device_command "$serial" 45 pull "$remote_segment" "$partial_segment" \
      >> "$destination/screenrecord.log" 2>&1; then
      echo "Could not pull owned Android recording: $remote_segment" \
        >> "$destination/screenrecord.log"
      rm -f "$partial_segment"
      touch "$control_dir/$label.failed"
      retry_exact_device_command "$serial" 8 shell rm -f "$remote_segment" \
        >> "$destination/screenrecord.log" 2>&1 || \
        touch "$control_dir/$label.cleanup-warning"
      return 1
    fi
    mv "$partial_segment" "$local_segment"
    if ! retry_exact_device_command "$serial" 8 shell rm -f "$remote_segment" \
      >> "$destination/screenrecord.log" 2>&1; then
      echo "Recording was saved, but remote cleanup did not finish: $remote_segment" \
        >> "$destination/screenrecord.log"
      touch "$control_dir/$label.cleanup-warning"
    fi
    segment=$((segment + 1))
  done
}

record_segments phone "$PHONE_SERIAL" "$phone_remote_dir" "$phone_dir" &
phone_recorder_loop_pid=$!
record_segments tablet "$TABLET_SERIAL" "$tablet_remote_dir" "$tablet_dir" &
tablet_recorder_loop_pid=$!

recorders_stopped=0
stop_recorders() {
  if [[ "$recorders_stopped" -eq 2 ]]; then
    return
  fi
  recorders_stopped=1
  touch "$control_dir/phone.stop" "$control_dir/tablet.stop" || true
  last_phone_pid=''
  last_tablet_pid=''
  for _ in $(seq 1 80); do
    active=0
    for spec in \
      "phone:$PHONE_SERIAL:$phone_recorder_loop_pid" \
      "tablet:$TABLET_SERIAL:$tablet_recorder_loop_pid"; do
      label="${spec%%:*}"
      remainder="${spec#*:}"
      serial="${remainder%%:*}"
      loop_pid="${remainder#*:}"
      if ! kill -0 "$loop_pid" 2>/dev/null; then
        continue
      fi
      active=1
      pid=''
      pid_file="$control_dir/$label.pid"
      pid="$(cat "$pid_file" 2>/dev/null | tr -d '\r\n' || true)"
      current_pid="$($ADB -s "$serial" shell pidof screenrecord 2>/dev/null \
        | tr -d '\r\n' || true)"
      last_pid_variable="last_${label}_pid"
      if [[ "$pid" =~ ^[0-9]+$ && "$current_pid" == "$pid" && \
            "$pid" != "${!last_pid_variable}" ]]; then
        "$ADB" -s "$serial" shell "kill -2 $pid" >/dev/null 2>&1 || true
        printf -v "$last_pid_variable" '%s' "$pid"
      fi
    done
    if [[ "$active" -eq 0 ]]; then
      break
    fi
    sleep 0.25
  done
  wait "$phone_recorder_loop_pid" 2>/dev/null || true
  wait "$tablet_recorder_loop_pid" 2>/dev/null || true
  recorders_stopped=2
}
trap 'stop_recorders' INT TERM EXIT

ready_deadline=$((SECONDS + 15))
while [[ ! -s "$control_dir/phone.ready" || ! -s "$control_dir/tablet.ready" ]]; do
  if (( SECONDS >= ready_deadline )); then
    echo 'Both native recorders did not become ready.' >&2
    exit 4
  fi
  if ! kill -0 "$phone_recorder_loop_pid" 2>/dev/null || \
     ! kill -0 "$tablet_recorder_loop_pid" 2>/dev/null; then
    echo 'A native recorder exited before both devices became ready.' >&2
    exit 4
  fi
  sleep 0.25
done

phone_first_ns="$(tr -d '\r\n' < "$control_dir/phone.ready")"
tablet_first_ns="$(tr -d '\r\n' < "$control_dir/tablet.ready")"
{
  printf 'phone_serial\t%s\n' "$PHONE_SERIAL"
  printf 'tablet_serial\t%s\n' "$TABLET_SERIAL"
  printf 'phone_first_segment_ns\t%s\n' "$phone_first_ns"
  printf 'tablet_first_segment_ns\t%s\n' "$tablet_first_ns"
  printf 'first_segment_start_delta_ms\t%s\n' "$(( (tablet_first_ns - phone_first_ns) / 1000000 ))"
  printf 'maximum_complete_seconds\t%s\n' "$duration"
  printf 'native_segment_seconds\t170\n'
  printf 'requested_bit_rate\t%s\n' "$bit_rate"
  printf 'phone_requested_max_edge\t%s\n' "${phone_max_edge:-native}"
  printf 'tablet_requested_max_edge\t%s\n' "${tablet_max_edge:-native}"
} > "$output_dir/recording-session.tsv"

command_status=0
set +e
if (( ${#showcase_command[@]} > 0 )); then
  timeout --signal=INT --kill-after=30s "${duration}s" "${showcase_command[@]}"
  command_status=$?
else
  sleep "$duration"
fi
set -e
stop_recorders
trap - INT TERM EXIT
retry_exact_device_command "$PHONE_SERIAL" 8 shell rmdir "$phone_remote_dir" \
  >> "$phone_dir/screenrecord.log" 2>&1 || \
  touch "$control_dir/phone.cleanup-warning"
retry_exact_device_command "$TABLET_SERIAL" 8 shell rmdir "$tablet_remote_dir" \
  >> "$tablet_dir/screenrecord.log" 2>&1 || \
  touch "$control_dir/tablet.cleanup-warning"

{
  for label in phone tablet; do
    if [[ -e "$control_dir/$label.cleanup-warning" ]]; then
      printf '%s\twarning\n' "$label"
    else
      printf '%s\tclean\n' "$label"
    fi
  done
} > "$output_dir/recording-cleanup.tsv"

if [[ -e "$control_dir/phone.failed" || -e "$control_dir/tablet.failed" ]]; then
  echo 'At least one native recorder failed.' >&2
  if [[ "$command_status" -eq 0 ]]; then command_status=1; fi
fi

collect_after() {
  local serial="$1"
  local destination="$2"
  local collection_status=0
  if ! timeout --signal=TERM --kill-after=2s 20s \
      "$ADB" -s "$serial" exec-out screencap -p \
      > "$destination/after.png"; then
    echo "Could not collect final screenshot from $serial." \
      >> "$destination/screenrecord.log"
    collection_status=1
  fi
  if ! timeout --signal=TERM --kill-after=2s 20s \
      "$ADB" -s "$serial" logcat -d -v threadtime \
      > "$destination/logcat.txt"; then
    echo "Could not collect logcat from $serial." \
      >> "$destination/screenrecord.log"
    collection_status=1
  fi
  if ! timeout --signal=TERM --kill-after=2s 20s \
      "$ADB" -s "$serial" shell dumpsys media.codec \
      > "$destination/media-codec.txt"; then
    echo "Could not collect media codec diagnostics from $serial." \
      >> "$destination/screenrecord.log"
    collection_status=1
  fi
  if ! timeout --signal=TERM --kill-after=2s 20s \
      "$ADB" -s "$serial" shell dumpsys SurfaceFlinger --list \
      > "$destination/surfaceflinger-layers.txt"; then
    echo "Could not collect SurfaceFlinger diagnostics from $serial." \
      >> "$destination/screenrecord.log"
    collection_status=1
  fi
  if ! timeout --signal=TERM --kill-after=2s 20s \
      "$ADB" -s "$serial" shell dumpsys display \
      > "$destination/display-after.txt"; then
    echo "Could not collect final display diagnostics from $serial." \
      >> "$destination/screenrecord.log"
    collection_status=1
  fi

  if ! find "$destination/segments" -type f -name '*.mp4' -size +4096c \
      -print0 | sort -z | xargs -0 -r sha256sum \
      > "$destination/native-segments.sha256"; then
    echo "Could not hash native MP4 segments for $serial." \
      >> "$destination/screenrecord.log"
    collection_status=1
  fi
  if [[ ! -s "$destination/native-segments.sha256" ]]; then
    echo "No nontrivial native MP4 segment was captured for $serial." >&2
    collection_status=1
  elif command -v ffmpeg >/dev/null 2>&1; then
    local concat_file="$destination/segments.concat.txt"
    : > "$concat_file"
    while IFS= read -r -d '' segment; do
      local absolute_segment
      absolute_segment="$(readlink -f "$segment")"
      local escaped="${absolute_segment//\'/\'\\\'\'}"
      printf "file '%s'\n" "$escaped" >> "$concat_file"
    done < <(find "$destination/segments" -type f -name '*.mp4' -size +4096c -print0 | sort -z)
    if ! ffmpeg -hide_banner -loglevel error -y \
        -f concat -safe 0 -i "$concat_file" -c copy \
        "$destination/native.mp4"; then
      echo "Could not concatenate native MP4 segments for $serial." \
        >> "$destination/screenrecord.log"
      collection_status=1
    elif ! sha256sum "$destination/native.mp4" \
        > "$destination/native.mp4.sha256"; then
      echo "Could not hash the native MP4 for $serial." \
        >> "$destination/screenrecord.log"
      collection_status=1
    elif command -v ffprobe >/dev/null 2>&1 && \
        ! ffprobe -v error \
          -select_streams v:0 \
          -show_entries stream=codec_name,width,height,r_frame_rate,avg_frame_rate,duration \
          -of json "$destination/native.mp4" \
          > "$destination/native.ffprobe.json"; then
      echo "Could not inspect the native MP4 for $serial." \
        >> "$destination/screenrecord.log"
      collection_status=1
    fi
  fi
  return "$collection_status"
}

evidence_status=0
if ! collect_after "$PHONE_SERIAL" "$phone_dir"; then
  evidence_status=1
fi
if ! collect_after "$TABLET_SERIAL" "$tablet_dir"; then
  evidence_status=1
fi
if [[ "$command_status" -eq 0 && "$evidence_status" -ne 0 ]]; then
  command_status="$evidence_status"
fi

printf 'Serial-labeled native evidence: %s\n' "$output_dir"
exit "$command_status"
