#!/usr/bin/env bash
set -euo pipefail

usage() {
  cat <<'EOF'
Usage:
  run_together_smoke.sh --session <session.env> --host-apk <apk>
    --guest-apk <apk> --driver <dart-file> --target <dart-file>
    --room <room> [options]

Options:
  --output <directory>  Role-specific output root
  --server <hostname>   Syncplay server (default: syncplay.pl)
  --port <integer>      Syncplay port (default: 8995)
  --video-url <url>     URL compiled into the prebuilt APKs
                        (default: http://10.0.2.2:18765/sync-fixture.mp4)
  --timeout <duration>  GNU timeout duration for each drive (default: 330s)

The APKs must already contain matching TOGETHER_ROOM, SYNCPLAY_SERVER and
SYNCPLAY_PORT dart defines, with TOGETHER_ROLE set to host and guest.
EOF
}

session_file=''
host_apk=''
guest_apk=''
driver=''
target=''
room=''
server='syncplay.pl'
port=8995
video_url="${TOGETHER_VIDEO_URL:-http://10.0.2.2:18765/sync-fixture.mp4}"
drive_timeout='330s'
output_dir=''

while (( $# > 0 )); do
  case "$1" in
    --session) session_file="${2:-}"; shift 2 ;;
    --host-apk) host_apk="${2:-}"; shift 2 ;;
    --guest-apk) guest_apk="${2:-}"; shift 2 ;;
    --driver) driver="${2:-}"; shift 2 ;;
    --target) target="${2:-}"; shift 2 ;;
    --room) room="${2:-}"; shift 2 ;;
    --server) server="${2:-}"; shift 2 ;;
    --port) port="${2:-}"; shift 2 ;;
    --video-url) video_url="${2:-}"; shift 2 ;;
    --timeout) drive_timeout="${2:-}"; shift 2 ;;
    --output) output_dir="${2:-}"; shift 2 ;;
    -h|--help) usage; exit 0 ;;
    *) echo "Unknown argument: $1" >&2; usage >&2; exit 2 ;;
  esac
done

for required in "$session_file" "$host_apk" "$guest_apk" "$driver" "$target"; do
  if [[ ! -f "$required" ]]; then
    echo "Required file does not exist: $required" >&2
    exit 2
  fi
done
if [[ ! "$room" =~ ^[A-Za-z0-9._-]+$ ]]; then
  echo 'A safe, unique --room value is required.' >&2
  exit 2
fi
if [[ -z "$server" || "$server" =~ [[:space:]] ]]; then
  echo '--server must be a nonempty hostname without whitespace.' >&2
  exit 2
fi
if [[ ! "$port" =~ ^[0-9]+$ ]] || (( port < 1 || port > 65535 )); then
  echo '--port must be an integer from 1 through 65535.' >&2
  exit 2
fi
if [[ ! "$video_url" =~ ^https?://[^[:space:]]+$ ]]; then
  echo '--video-url must be an HTTP(S) URL without whitespace.' >&2
  exit 2
fi
if [[ ! "$drive_timeout" =~ ^[1-9][0-9]*[smh]?$ ]]; then
  echo '--timeout must be a positive GNU timeout duration such as 330s.' >&2
  exit 2
fi

# session.env is generated by launch_two_avds.sh and contains shell-escaped
# values only. Do not use an untrusted file here.
source "$session_file"
: "${PHONE_SERIAL:?session is missing PHONE_SERIAL}"
: "${TABLET_SERIAL:?session is missing TABLET_SERIAL}"
: "${SESSION_DIR:?session is missing SESSION_DIR}"

output_dir="${output_dir:-$SESSION_DIR/together-smoke}"
host_output="$output_dir/host-$PHONE_SERIAL"
guest_output="$output_dir/guest-$TABLET_SERIAL"
host_driver_output='build/android-multi-device-artifacts/host'
guest_driver_output='build/android-multi-device-artifacts/guest'
mkdir -p "$output_dir"
if find "$output_dir" -mindepth 1 -print -quit | grep -q .; then
  echo "Smoke output must be empty before a fresh run: $output_dir" >&2
  exit 3
fi
mkdir -p "$host_output" "$guest_output"
mkdir -p "$host_driver_output" "$guest_driver_output"
for driver_output in "$host_driver_output" "$guest_driver_output"; do
  if find "$driver_output" -mindepth 1 -print -quit | grep -q .; then
    echo "Driver output must be empty before a fresh run: $driver_output" >&2
    exit 3
  fi
done

{
  printf 'room\t%s\n' "$room"
  printf 'server\t%s\n' "$server"
  printf 'port\t%s\n' "$port"
  printf 'video_url\t%s\n' "$video_url"
  printf 'host_role\thost\n'
  printf 'host_serial\t%s\n' "$PHONE_SERIAL"
  printf 'host_apk\t%s\n' "$host_apk"
  printf 'host_vmservice_port\t39101\n'
  printf 'host_driver_output\t%s\n' "$host_driver_output"
  printf 'guest_role\tguest\n'
  printf 'guest_serial\t%s\n' "$TABLET_SERIAL"
  printf 'guest_apk\t%s\n' "$guest_apk"
  printf 'guest_vmservice_port\t39102\n'
  printf 'guest_driver_output\t%s\n' "$guest_driver_output"
  printf 'driver\t%s\n' "$driver"
  printf 'target\t%s\n' "$target"
  printf 'started_utc\t%s\n' "$(date -u +%Y-%m-%dT%H:%M:%SZ)"
} > "$output_dir/command-environment.tsv"
sha256sum "$host_apk" > "$host_output/application.apk.sha256"
sha256sum "$guest_apk" > "$guest_output/application.apk.sha256"

run_role() {
  local role="$1"
  local serial="$2"
  local apk="$3"
  local vmservice_port="$4"
  local destination="$5"
  set +e
  TOGETHER_ROLE="$role" \
  TOGETHER_ROOM="$room" \
  SYNCPLAY_SERVER="$server" \
  SYNCPLAY_PORT="$port" \
  TOGETHER_VIDEO_URL="$video_url" \
  timeout --signal=INT --kill-after=30s "$drive_timeout" flutter drive \
      --no-pub \
      --driver="$driver" \
      --target="$target" \
      --use-application-binary="$apk" \
      --host-vmservice-port="$vmservice_port" \
      -d "$serial" \
      2>&1 | tee "$destination/flutter-drive.log"
  printf '%s\n' "${PIPESTATUS[0]}" > "$destination/exit-code.txt"
}

run_role host "$PHONE_SERIAL" "$host_apk" 39101 "$host_output" &
host_drive_pid=$!
sleep 2
run_role guest "$TABLET_SERIAL" "$guest_apk" 39102 "$guest_output" &
guest_drive_pid=$!

set +e
wait "$host_drive_pid"
wait "$guest_drive_pid"
set -e

host_status="$(tr -d '\r\n' < "$host_output/exit-code.txt")"
guest_status="$(tr -d '\r\n' < "$guest_output/exit-code.txt")"
mkdir -p "$host_output/driver" "$guest_output/driver"
cp -a "$host_driver_output/." "$host_output/driver/"
cp -a "$guest_driver_output/." "$guest_output/driver/"
printf 'Host drive exit: %s; guest drive exit: %s\n' "$host_status" "$guest_status"
if [[ "$host_status" -ne 0 || "$guest_status" -ne 0 ]]; then
  exit 1
fi
