#!/usr/bin/env bash
set -euo pipefail

usage() {
  cat <<'EOF'
Usage:
  run_together_smoke.sh --session <session.env> --host-apk <apk>
    --guest-apk <apk> --driver <dart-file> --target <dart-file>
    --room <room> [options]

Options:
  --output <directory>  Role-specific output root
  --driver-output <directory> Root written by the selected integration driver
  --server <hostname>   Syncplay server (default: syncplay.pl)
  --port <integer>      Syncplay port (default: 8995)
  --video-url <url>     URL compiled into the prebuilt APKs
                        (default: http://10.0.2.2:18765/sync-fixture.mp4)
  --timeout <duration>  GNU timeout duration for each drive (default: 330s)

The APKs must already contain matching TOGETHER_ROOM, SYNCPLAY_SERVER and
SYNCPLAY_PORT dart defines, with TOGETHER_ROLE set to host and guest.
EOF
}

session_file=''
host_apk=''
guest_apk=''
driver=''
target=''
room=''
server='syncplay.pl'
port=8995
video_url="${TOGETHER_VIDEO_URL:-http://10.0.2.2:18765/sync-fixture.mp4}"
drive_timeout='330s'
output_dir=''
driver_output_root='build/android-multi-device-artifacts'

while (( $# > 0 )); do
  case "$1" in
    --session) session_file="${2:-}"; shift 2 ;;
    --host-apk) host_apk="${2:-}"; shift 2 ;;
    --guest-apk) guest_apk="${2:-}"; shift 2 ;;
    --driver) driver="${2:-}"; shift 2 ;;
    --target) target="${2:-}"; shift 2 ;;
    --room) room="${2:-}"; shift 2 ;;
    --server) server="${2:-}"; shift 2 ;;
    --port) port="${2:-}"; shift 2 ;;
    --video-url) video_url="${2:-}"; shift 2 ;;
    --timeout) drive_timeout="${2:-}"; shift 2 ;;
    --output) output_dir="${2:-}"; shift 2 ;;
    --driver-output) driver_output_root="${2:-}"; shift 2 ;;
    -h|--help) usage; exit 0 ;;
    *) echo "Unknown argument: $1" >&2; usage >&2; exit 2 ;;
  esac
done

for required in "$session_file" "$host_apk" "$guest_apk" "$driver" "$target"; do
  if [[ ! -f "$required" ]]; then
    echo "Required file does not exist: $required" >&2
    exit 2
  fi
done
if [[ ! "$room" =~ ^[A-Za-z0-9._-]+$ ]]; then
  echo 'A safe, unique --room value is required.' >&2
  exit 2
fi
if [[ -z "$server" || "$server" =~ [[:space:]] ]]; then
  echo '--server must be a nonempty hostname without whitespace.' >&2
  exit 2
fi
if [[ ! "$port" =~ ^[0-9]+$ ]] || (( port < 1 || port > 65535 )); then
  echo '--port must be an integer from 1 through 65535.' >&2
  exit 2
fi
if [[ ! "$video_url" =~ ^https?://[^[:space:]]+$ ]]; then
  echo '--video-url must be an HTTP(S) URL without whitespace.' >&2
  exit 2
fi
if [[ ! "$drive_timeout" =~ ^[1-9][0-9]*[smh]?$ ]]; then
  echo '--timeout must be a positive GNU timeout duration such as 330s.' >&2
  exit 2
fi

# session.env is generated by launch_two_avds.sh and contains shell-escaped
# values only. Do not use an untrusted file here.
source "$session_file"
: "${PHONE_SERIAL:?session is missing PHONE_SERIAL}"
: "${TABLET_SERIAL:?session is missing TABLET_SERIAL}"
: "${SESSION_DIR:?session is missing SESSION_DIR}"
: "${ADB:?session is missing ADB}"
if [[ ! -x "$ADB" ]]; then
  echo "Session adb is not executable: $ADB" >&2
  exit 2
fi

output_dir="${output_dir:-$SESSION_DIR/together-smoke}"
host_output="$output_dir/host-$PHONE_SERIAL"
guest_output="$output_dir/guest-$TABLET_SERIAL"
host_driver_output="$driver_output_root/host"
guest_driver_output="$driver_output_root/guest"
mkdir -p "$output_dir"
if find "$output_dir" -mindepth 1 -print -quit | grep -q .; then
  echo "Smoke output must be empty before a fresh run: $output_dir" >&2
  exit 3
fi
mkdir -p "$host_output" "$guest_output"
mkdir -p "$host_driver_output" "$guest_driver_output"
for driver_output in "$host_driver_output" "$guest_driver_output"; do
  if find "$driver_output" -mindepth 1 -print -quit | grep -q .; then
    echo "Driver output must be empty before a fresh run: $driver_output" >&2
    exit 3
  fi
done

{
  printf 'room\t%s\n' "$room"
  printf 'server\t%s\n' "$server"
  printf 'port\t%s\n' "$port"
  printf 'video_url\t%s\n' "$video_url"
  printf 'host_role\thost\n'
  printf 'host_serial\t%s\n' "$PHONE_SERIAL"
  printf 'host_apk\t%s\n' "$host_apk"
  printf 'host_vmservice_port\t39101\n'
  printf 'host_driver_output\t%s\n' "$host_driver_output"
  printf 'guest_role\tguest\n'
  printf 'guest_serial\t%s\n' "$TABLET_SERIAL"
  printf 'guest_apk\t%s\n' "$guest_apk"
  printf 'guest_vmservice_port\t39102\n'
  printf 'guest_driver_output\t%s\n' "$guest_driver_output"
  printf 'driver\t%s\n' "$driver"
  printf 'target\t%s\n' "$target"
  printf 'started_utc\t%s\n' "$(date -u +%Y-%m-%dT%H:%M:%SZ)"
} > "$output_dir/command-environment.tsv"
sha256sum "$host_apk" > "$host_output/application.apk.sha256"
sha256sum "$guest_apk" > "$guest_output/application.apk.sha256"

run_adb_bounded() {
  timeout --signal=TERM --kill-after=2s 8s "$ADB" "$@"
}

normalize_component() {
  local component="$1"
  local package=''
  local activity=''
  if [[ "$component" != */* ]]; then
    return 1
  fi
  package="${component%%/*}"
  activity="${component#*/}"
  if [[ "$activity" == .* ]]; then
    activity="$package$activity"
  fi
  printf '%s/%s\n' "$package" "$activity"
}

capture_device_diagnostics() {
  local role="$1"
  local serial="$2"
  local destination="$3/diagnostics"
  mkdir -p "$destination"
  date -u +%Y-%m-%dT%H:%M:%SZ > "$destination/captured-utc.txt"
  run_adb_bounded -s "$serial" get-state > "$destination/adb-state.txt" 2>&1 || true
  run_adb_bounded -s "$serial" shell getprop > "$destination/getprop.txt" 2>&1 || true
  {
    printf 'device_provisioned='
    run_adb_bounded -s "$serial" shell settings get global device_provisioned 2>/dev/null | tr -d '\r' || true
    printf 'user_setup_complete='
    run_adb_bounded -s "$serial" shell settings get secure user_setup_complete 2>/dev/null | tr -d '\r' || true
    printf 'boot_completed='
    run_adb_bounded -s "$serial" shell getprop sys.boot_completed 2>/dev/null | tr -d '\r' || true
    printf 'bootanim='
    run_adb_bounded -s "$serial" shell getprop init.svc.bootanim 2>/dev/null | tr -d '\r' || true
  } > "$destination/readiness.txt"
  run_adb_bounded -s "$serial" shell dumpsys window displays \
    > "$destination/window-displays.txt" 2>&1 || true
  run_adb_bounded -s "$serial" shell dumpsys activity activities \
    > "$destination/activity-activities.txt" 2>&1 || true
  run_adb_bounded -s "$serial" shell pidof com.meowwatch.meowwatch_mobile \
    > "$destination/app-pid.txt" 2>&1 || true
  run_adb_bounded forward --list > "$destination/adb-forward-list.txt" 2>&1 || true
  run_adb_bounded -s "$serial" logcat -d -t 1200 \
    > "$destination/logcat-tail.txt" 2>&1 || true
  printf '%s\t%s\n' "$role" "$serial" > "$destination/device.tsv"
}

wait_for_interactive_device() {
  local role="$1"
  local serial="$2"
  local destination="$3"
  local started="$SECONDS"
  local deadline=$((SECONDS + 120))
  local state=''
  local boot=''
  local bootanim=''
  local provisioned=''
  local setup=''
  local home=''
  local normalized_home=''
  local focus=''
  local focus_component=''
  local normalized_focus=''
  while (( SECONDS < deadline )); do
    state="$(run_adb_bounded -s "$serial" get-state 2>/dev/null | tr -d '\r' || true)"
    boot="$(run_adb_bounded -s "$serial" shell getprop sys.boot_completed 2>/dev/null | tr -d '\r' || true)"
    bootanim="$(run_adb_bounded -s "$serial" shell getprop init.svc.bootanim 2>/dev/null | tr -d '\r' || true)"
    provisioned="$(run_adb_bounded -s "$serial" shell settings get global device_provisioned 2>/dev/null | tr -d '\r' || true)"
    setup="$(run_adb_bounded -s "$serial" shell settings get secure user_setup_complete 2>/dev/null | tr -d '\r' || true)"
    if [[ "$state" == 'device' && "$boot" == '1' && "$bootanim" == 'stopped' && "$provisioned" == '1' && "$setup" == '1' ]]; then
      run_adb_bounded -s "$serial" shell input keyevent 3 >/dev/null 2>&1 || true
      sleep 1
      home="$(run_adb_bounded -s "$serial" shell cmd package resolve-activity --brief \
        -a android.intent.action.MAIN -c android.intent.category.HOME \
        2>/dev/null | tr -d '\r' | tail -n 1 || true)"
      normalized_home="$(normalize_component "$home" 2>/dev/null || true)"
      focus="$(run_adb_bounded -s "$serial" shell dumpsys window displays 2>/dev/null \
        | grep -m 1 'mCurrentFocus=' || true)"
      focus_component=''
      normalized_focus=''
      if [[ "$focus" =~ ([[:alnum:]_.]+)/([[:alnum:]_.$]+) ]]; then
        focus_component="${BASH_REMATCH[1]}/${BASH_REMATCH[2]}"
        normalized_focus="$(normalize_component "$focus_component" 2>/dev/null || true)"
      fi
      if [[ -n "$home" && "$home" != *'No activity found'* && \
            "$home" != *'googlesdksetup'* && "$home" != *'FallbackHome'* && \
            -n "$normalized_home" && -n "$normalized_focus" && \
            "$normalized_focus" == "$normalized_home" && \
            "$focus" != *'Application Not Responding'* ]]; then
        {
          printf 'role\t%s\n' "$role"
          printf 'serial\t%s\n' "$serial"
          printf 'ready_seconds\t%s\n' "$((SECONDS - started))"
          printf 'resolved_home\t%s\n' "$home"
          printf 'focus\t%s\n' "$focus"
        } > "$destination/readiness.tsv"
        return 0
      fi
    fi
    sleep 2
  done
  echo "$role device $serial did not reach a provisioned interactive Home within 120 seconds." >&2
  capture_device_diagnostics "$role" "$serial" "$destination"
  return 1
}

wait_for_vm_service_attach() {
  local role="$1"
  local serial="$2"
  local drive_pid="$3"
  local destination="$4"
  local deadline=$((SECONDS + 120))
  while (( SECONDS < deadline )); do
    if grep -Fq 'VMServiceFlutterDriver: Connected to Flutter application.' \
        "$destination/flutter-drive.log" 2>/dev/null; then
      printf '%s\n' "$(date -u +%Y-%m-%dT%H:%M:%SZ)" \
        > "$destination/vm-service-attached-utc.txt"
      return 0
    fi
    if ! kill -0 "$drive_pid" 2>/dev/null; then
      echo "$role drive exited before its VM Service attached on $serial." >&2
      capture_device_diagnostics "$role" "$serial" "$destination"
      return 1
    fi
    sleep 2
  done
  echo "$role VM Service did not attach on $serial within 120 seconds." >&2
  capture_device_diagnostics "$role" "$serial" "$destination"
  return 1
}

phone_ready_pid=''
tablet_ready_pid=''
wait_for_interactive_device host "$PHONE_SERIAL" "$host_output" &
phone_ready_pid=$!
wait_for_interactive_device guest "$TABLET_SERIAL" "$guest_output" &
tablet_ready_pid=$!
set +e
wait "$phone_ready_pid"
phone_ready_status=$?
wait "$tablet_ready_pid"
tablet_ready_status=$?
set -e
if [[ "$phone_ready_status" -ne 0 || "$tablet_ready_status" -ne 0 ]]; then
  exit 1
fi

run_role() {
  local role="$1"
  local serial="$2"
  local apk="$3"
  local vmservice_port="$4"
  local destination="$5"
  local -a native_guard=()
  if [[ "$target" == 'integration_test/production_together_test.dart' ]]; then
    native_guard=(python3 -m tools.production_together.anr_guard
      --adb "$ADB" --serial "$serial" --role "$role"
      --output "$destination/native-anr"
      --failure-latch "$output_dir/native-anr-failure.json" --)
  fi
  set +e
  TOGETHER_ROLE="$role" \
  TOGETHER_ROOM="$room" \
  SYNCPLAY_SERVER="$server" \
  SYNCPLAY_PORT="$port" \
  TOGETHER_VIDEO_URL="$video_url" \
  "${native_guard[@]}" timeout --signal=INT --kill-after=30s "$drive_timeout" flutter drive \
      --no-pub \
      --driver="$driver" \
      --target="$target" \
      --use-application-binary="$apk" \
      --host-vmservice-port="$vmservice_port" \
      -d "$serial" \
      2>&1 | tee "$destination/flutter-drive.log"
  printf '%s\n' "${PIPESTATUS[0]}" > "$destination/exit-code.txt"
}

run_role host "$PHONE_SERIAL" "$host_apk" 39101 "$host_output" &
host_drive_pid=$!
guest_drive_pid=''
if wait_for_vm_service_attach host "$PHONE_SERIAL" "$host_drive_pid" "$host_output"; then
  run_role guest "$TABLET_SERIAL" "$guest_apk" 39102 "$guest_output" &
  guest_drive_pid=$!
  wait_for_vm_service_attach guest "$TABLET_SERIAL" "$guest_drive_pid" "$guest_output" || true
fi

set +e
wait "$host_drive_pid"
if [[ -n "$guest_drive_pid" ]]; then
  wait "$guest_drive_pid"
else
  printf '125\n' > "$guest_output/exit-code.txt"
  printf 'Guest drive was not started because the host VM Service did not attach.\n' \
    > "$guest_output/flutter-drive.log"
fi
set -e

host_status="$(tr -d '\r\n' < "$host_output/exit-code.txt")"
guest_status="$(tr -d '\r\n' < "$guest_output/exit-code.txt")"
host_final_status=0
guest_final_status=0
if [[ "$target" == 'integration_test/production_together_test.dart' ]]; then
  # The earlier role can finish before its peer. Recheck both native apps using
  # their original baselines and observed PIDs, even if either driver failed.
  # Each guard bounds its own commands; one failure must not skip its peer.
  set +e
  for role in host guest; do
    if [[ "$role" == host ]]; then
      serial="$PHONE_SERIAL"
      destination="$host_output"
    else
      serial="$TABLET_SERIAL"
      destination="$guest_output"
    fi
    python3 -m tools.production_together.anr_guard \
      --adb "$ADB" --serial "$serial" --role "$role" \
      --output "$destination/native-anr-final" \
      --failure-latch "$output_dir/native-anr-failure.json" \
      --after-roles "$destination/native-anr"
    final_status=$?
    printf '%s\n' "$final_status" > "$destination/native-anr-final-exit-code.txt"
    if [[ "$role" == host ]]; then
      host_final_status="$final_status"
    else
      guest_final_status="$final_status"
    fi
  done
  set -e
  printf 'role\tdriverExit\tfinalGuardExit\nhost\t%s\t%s\nguest\t%s\t%s\n' \
    "$host_status" "$host_final_status" "$guest_status" "$guest_final_status" \
    > "$output_dir/native-anr-exits.tsv"
fi
mkdir -p "$host_output/driver" "$guest_output/driver"
cp -a "$host_driver_output/." "$host_output/driver/"
cp -a "$guest_driver_output/." "$guest_output/driver/"
printf 'Host drive exit: %s; guest drive exit: %s\n' "$host_status" "$guest_status"
if [[ "$host_status" -ne 0 || "$guest_status" -ne 0 || "$host_final_status" -ne 0 || "$guest_final_status" -ne 0 ]]; then
  capture_device_diagnostics host "$PHONE_SERIAL" "$host_output"
  capture_device_diagnostics guest "$TABLET_SERIAL" "$guest_output"
  exit 1
fi
