#!/usr/bin/env bash
set -euo pipefail

usage() {
  echo 'Usage: stop_two_avds.sh <session.env> [--delete-avds]'
}

if [[ "${1:-}" == '-h' || "${1:-}" == '--help' ]]; then
  usage
  exit 0
fi
if [[ $# -lt 1 || $# -gt 2 ]]; then
  usage >&2
  exit 2
fi

session_file="$1"
delete_avds="${2:-}"
if [[ ! -f "$session_file" ]]; then
  echo "Session file does not exist: $session_file" >&2
  exit 2
fi
if [[ -n "$delete_avds" && "$delete_avds" != '--delete-avds' ]]; then
  usage >&2
  exit 2
fi

# session.env is generated by launch_two_avds.sh and contains shell-escaped
# values only. Do not use an untrusted file here.
source "$session_file"
: "${ADB:?session is missing ADB}"
: "${AVDMANAGER:?session is missing AVDMANAGER}"
: "${AVD_HOME:?session is missing AVD_HOME}"
: "${PHONE_SERIAL:?session is missing PHONE_SERIAL}"
: "${TABLET_SERIAL:?session is missing TABLET_SERIAL}"

"$ADB" -s "$PHONE_SERIAL" emu kill >/dev/null 2>&1 || true
"$ADB" -s "$TABLET_SERIAL" emu kill >/dev/null 2>&1 || true

for pid_name in PHONE_EMULATOR_PID TABLET_EMULATOR_PID; do
  pid="${!pid_name:-}"
  if [[ "$pid" =~ ^[0-9]+$ ]]; then
    for _ in $(seq 1 40); do
      if ! kill -0 "$pid" 2>/dev/null; then
        break
      fi
      sleep 0.25
    done
    if kill -0 "$pid" 2>/dev/null; then
      kill -TERM "$pid"
    fi
  fi
done

if [[ "$delete_avds" == '--delete-avds' ]]; then
  ANDROID_AVD_HOME="$AVD_HOME" "$AVDMANAGER" delete avd --name "$PHONE_AVD"
  ANDROID_AVD_HOME="$AVD_HOME" "$AVDMANAGER" delete avd --name "$TABLET_AVD"
fi

echo 'Task-owned Android emulator instances stopped.'
