#!/usr/bin/env bash
set -euo pipefail

# Diagnostic-only path. The production Together runner and its acceptance gates
# remain independent of these local-player recordings.
runtime_root='build/android-motion-probe'
fixture_root="$runtime_root/fixture"
server_state="$runtime_root/fixture-server"
sessions_root="$runtime_root/sessions"
probe_output="$runtime_root/evidence"
apk='build/app/outputs/flutter-apk/app-profile.apk'
session_file=''

for required in "$fixture_root/sync-fixture.mp4" "$apk" 'build/android-native-ui/native-ui-observer.apk'; do
  if [[ ! -s "$required" ]]; then
    echo "Motion probe input is missing: $required" >&2
    exit 2
  fi
done
mkdir -p "$runtime_root"
if [[ -e "$sessions_root" || -e "$server_state" || -e "$probe_output" ]]; then
  echo 'Motion probe session, server and evidence paths must start unused.' >&2
  exit 2
fi
flutter --version --machine > "$runtime_root/flutter-version.json"
{
  printf 'head\t%s\n' "$(git rev-parse HEAD)"
  printf 'build_mode\tprofile\n'
  printf 'target\tlib/main.dart\n'
  printf 'apk_sha256\t%s\n' "$(sha256sum "$apk" | awk '{print $1}')"
  printf 'fixture_sha256\t%s\n' "$(sha256sum "$fixture_root/sync-fixture.mp4" | awk '{print $1}')"
  printf 'observer_sha256\t%s\n' "$(sha256sum build/android-native-ui/native-ui-observer.apk | awk '{print $1}')"
} > "$runtime_root/build-provenance.tsv"

cleanup() {
  local original_status=$?
  trap - EXIT
  set +e
  if [[ -n "$session_file" && -f "$session_file" ]]; then
    bash tools/android_multi_device/stop_two_avds.sh "$session_file" --delete-avds \
      > "$runtime_root/avd-cleanup.log" 2>&1
    printf 'avd_cleanup_exit\t%s\n' "$?" >> "$runtime_root/cleanup.tsv"
  fi
  if [[ -f "$server_state/server.env" ]]; then
    bash tools/android_multi_device/stop_fixture_server.sh "$server_state/server.env" \
      > "$runtime_root/server-cleanup.log" 2>&1
    printf 'server_cleanup_exit\t%s\n' "$?" >> "$runtime_root/cleanup.tsv"
  fi
  exit "$original_status"
}
trap cleanup EXIT

bash tools/android_multi_device/start_fixture_server.sh \
  --fixture "$fixture_root/sync-fixture.mp4" --state "$server_state" --port 18765
bash tools/android_multi_device/launch_two_avds.sh "$sessions_root" \
  > "$runtime_root/avd-launch.log" 2>&1
mapfile -t sessions < <(find "$sessions_root" -name session.env -type f -print)
if [[ "${#sessions[@]}" -ne 1 ]]; then
  echo 'Motion probe requires exactly one owned two-AVD session.' >&2
  exit 3
fi
session_file="${sessions[0]}"
# The source file is generated by the scoped launcher and shell-escapes its values.
source "$session_file"
if [[ ! -x "$ADB" ]]; then
  echo 'The owned emulator session has no executable Android platform-tools adb.' >&2
  exit 3
fi
export PATH="$(dirname "$ADB"):$PATH"
python3 -m tools.android_motion_probe.run \
  --apk "$apk" \
  --fixture "$fixture_root/sync-fixture.mp4" \
  --output "$probe_output" \
  --phone-serial "$PHONE_SERIAL" --tablet-serial "$TABLET_SERIAL" \
  --phone-avd "$PHONE_AVD" --tablet-avd "$TABLET_AVD" \
  --phone-emulator-pid "$PHONE_EMULATOR_PID" \
  --tablet-emulator-pid "$TABLET_EMULATOR_PID" \
  --seconds 30
